name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.1
        with:
          build_configuration: production
          base_href: /
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/foss-ucsc
